# Project Configuration
project:
  name: "encrypted_traffic_fingerprinting"
  version: "1.0.0"

# Data Collection Settings
collection:
  target_websites:
    - "https://www.google.com"
    - "https://www.facebook.com"
    - "https://www.youtube.com"
    - "https://www.amazon.com"
    - "https://www.wikipedia.org"
    - "https://www.twitter.com"
    - "https://www.instagram.com"
    - "https://www.linkedin.com"
    - "https://www.reddit.com"
    - "https://www.netflix.com"
    - "https://www.github.com"
    - "https://www.stackoverflow.com"
    - "https://www.medium.com"
    - "https://www.cnn.com"
    - "https://www.bbc.com"
    - "https://www.nytimes.com"
    - "https://www.apple.com"
    - "https://www.microsoft.com"
    - "https://www.adobe.com"
    - "https://www.spotify.com"
  
  visits_per_site: 100
  capture_duration: 30  # seconds
  interface: "en0"  # Default MacBook WiFi interface
  use_tor: false
  use_vpn: false
  headless: true

# Feature Extraction Settings
features:
  max_packets: 5000
  time_window: 60  # seconds
  packet_size_bins: 10
  extract_ja3: true
  normalize: true

# Model Training Settings
models:
  test_size: 0.3
  validation_size: 0.2
  random_state: 42
  cv_folds: 5
  
  classifiers:
    - name: "RandomForest"
      params:
        n_estimators: 100
        max_depth: 20
        random_state: 42
    - name: "SVM"
      params:
        kernel: "rbf"
        C: 1.0
        random_state: 42
    - name: "XGBoost"
      params:
        n_estimators: 100
        learning_rate: 0.1
        max_depth: 6
        random_state: 42

# Defense Settings
defense:
  padding:
    enabled: true
    target_size: 1500  # bytes
    random_padding: true
  
  timing:
    enabled: true
    jitter_range: [0, 100]  # milliseconds
    constant_rate: false
    rate_ms: 50

# Paths
paths:
  data: "data"
  results: "results"
  logs: "logs"
